---
apiVersion: v1
kind: Namespace
metadata:
  name: intergallactic
  labels:
    name: intergallactic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-server-deployment
  namespace: intergallactic
  labels:
    app: message-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: message-server
  template:
    metadata:
      labels:
        app: message-server
    spec:
      containers:
      - name: message-server
        image: renantarouco/ics-message-server
        ports:
        - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: message-server
  namespace: intergallactic
spec:
  type: LoadBalancer
  selector:
    app: message-server
  ports:
  - port: 7000
    targetPort: 7000