apiVersion: v1
kind: Service
metadata:
  labels:
    app: message-server
  name: message-server
  namespace: ics
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 7000
    port: 7000
    protocol: TCP
    targetPort: 7000
  selector:
    app: message-server
  type: LoadBalancer
