---
apiVersion: v1
kind: Namespace
metadata:
  name: ics
  labels:
    name: ics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: message-server
  name: message-server
  namespace: ics
spec:
  replicas: 3
  selector:
    matchLabels:
      app: message-server
  template:
    metadata:
      labels:
        app: message-server
    spec:
      containers:
      - name: message-server
        image: renantarouco/ics-message-server
        ports:
        - containerPort: 7000