#!/usr/bin/env sh
HOST="localhost"
PORT="7000"
NICKNAME=""

while [ $# -gt 0 ]
do
  KEY=$1
  case $KEY in
    -n|--nickname)
      NICKNAME=$2
      shift
      shift
      ;;
    -h|--host)
      HOST=$2
      shift
      shift
      ;;
    -p|--port)
      PORT=$2
      shift
      shift
      ;;
  esac
done

if [ "$NICKNAME" = "" ]; then
  echo "must inform nickname"
  exit 1
fi

echo "HOST     = $HOST"
echo "PORT     = $PORT"
echo "NICKNAME = $NICKNAME"

TOKEN=$(curl --request POST \
  --url http://$HOST:$PORT/auth \
  --header 'content-type: application/x-www-form-urlencoded' \
  --data nickname=$NICKNAME | jq -r ".token")

curl --include \
  --no-buffer \
  --header 'Accept: application/json' \
  --header "Authorization: Bearer $TOKEN" \
  --header "Connection: Upgrade" \
  --header "Upgrade: websocket" \
  --header "Host: $HOST:$PORT" \
  --header "Origin: http://example.com:80" \
  --header "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" \
  --header "Sec-WebSocket-Version: 13" \
  http://$HOST:$PORT/ws
